version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: java-commerce-api
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: W3lcome!
    ports:
      - "5432:5432"
    volumes:
      - pg_java_commerce_api_data:/var/lib/postgresql/data

volumes:
  pg_java_commerce_api_data:
